export const AUTH_SIGN_IN_CLIENT = 'AUTH_SIGN_IN_CLIENT';
export const AUTH_SIGN_IN_RESTAURANT = 'AUTH_SIGN_IN_RESTAURANT';
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const GET_SLOTS_SUCCESS = 'GET_SLOTS_SUCCESS';
export const GET_SLOTS_ERROR = 'GET_SLOTS_ERROR';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_ERROR =  'GET_REQUESTS_ERROR'; 
//RESTAURANT
export const GET_USER_HISTORY_SUCCESS = 'GET_USER_HISTORY_SUCCESS';
export const GET_USER_HISTORY_ERROR = 'GET_USER_HISTORY_ERROR';

export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS';
export const CREATE_TOKEN_ERROR = 'CREATE_TOKEN_ERROR';

export const GET_PROOF_OF_VAL = 'GET_PROOF_OF_VAL';

export const APPROVE_TOKEN_SUCCESS = 'APPROVE_TOKEN_SUCCESS';
export const APPROVE_TOKEN_ERROR = 'APPROVE_TOKEN_ERROR';

export const REJECT_TOKEN_SUCCESS = 'REJECT_TOKEN_SUCCESS';
export const REJECT_TOKEN_ERROR = 'REJECT_TOKEN_ERROR';
//CLIENT
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_ERROR = 'GET_RESTAURANTS_ERROR';
export const GET_RESTAURANT_TOKENS = 'GET_RESTAURANT_TOKENS';

export const APPLY_TOKEN_SUCCESS = "APPLY_TOKEN_SUCCESS";
export const APPLY_TOKEN_ERROR = "APPLY_TOKEN_ERROR";

export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';
export const GET_RESERVATIONS_ERROR = 'GET_RESERVATIONS_ERROR';

export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_ERROR = 'POST_REVIEW_ERROR';

export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';
